# Generated by Django 3.2.25 on 2024-09-27 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burger_app', '0003_menuhamburger'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=100000)),
            ],
        ),
        migrations.AlterField(
            model_name='menuhamburger',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='menu_hamburgers/'),
        ),
    ]
